INSERT INTO sushi_bars(name, rating)VALUES
('DaiwaSushi',4.5),
('SushiDokoroYamazaki',5),
('SUSHIZANMAIHonten',4.5),
('NemuroHanamaru', 4),
('MantenSushi',5),
('UmegaokaSushinomidoriSōhontenShibuya',4.5),
('SukiyabashiJiro', 4),
('KyubeyGinza',4.5),
('SukiyabashiJiroRoppongiHills',4.5),
('IwasaSushi',4.5),
('SushishoMasa',5),
('GENKISUSHIShibuya', 4),
('TsukijiSushiseiHonten',4.5),
('OtaSushi',4.5),
('HinatomaruAsakusa',4.5),
('NadeshikoSushi',4.5),
('SushiBarYasuda',4.5),
('UogashiNihonichiTachiguiSushi',4.5);
